---
- name: Create slackirc user
  user:
    name: slackirc
    system: yes
    createhome: yes
    home: /opt/slackirc
    state: present

- name: Install slack-irc
  npm:
    name: slack-irc
    state: latest
    global: yes
  register: slackirc_download_slackirc

- name: Generate slack-irc configurations
  become: yes
  become_user: slackirc
  template:
    src: slack-irc.json.j2
    dest: "/opt/slackirc/{{ irc_nickname }}.json"
    mode: "u=rw,g=,o="
  register: slackirc_generate_configs

- name: Generate systemd unit
  template:
    src: slack-irc.service.j2
    dest: "/etc/systemd/system/slack-irc-{{ irc_nickname }}.service"
  register: slackirc_generate_systemd

- name: Ensure the service has started
  systemd:
    name: "slack-irc-{{ irc_nickname }}"
    state: started
    enabled: yes
  register: slackirc_start_service

- name: Restart the service if necessary
  systemd:
    name: "slack-irc-{{ irc_nickname }}"
    state: restarted
    daemon_reload: yes
  when:
    - slackirc_start_service.changed == False
    - (slackirc_download_slackirc.changed == True) or
      (slackirc_generate_configs.changed == True) or
      (slackirc_generate_systemd.changed == True)

