---
- hosts: all
  gather_facts: False

- name: Servers
  hosts: servers
  become: yes
  become_user: root
  roles:
    - common
    - firewall
    - yubikey
    - apache2
    - letsencrypt

- name: Wiki
  hosts: web
  become: yes
  become_user: root
  roles:
    - apache2-mediawiki
    - mariadb
    - mediawiki
  vars:
    domain: ucilug.org
    cert_domain: ucilug.org
    upload_domain: uploads.ucilug.org
    enable_https: True
    enable_hsts: True
    referrer_policy: same-origin
    x_frame_options: SAMEORIGIN
    content_security_policy: "upgrade-insecure-requests; default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https://uploads.ucilug.org/ https://upload.wikimedia.org/; media-src 'self' https://upload.wikimedia.org/; style-src 'self' 'unsafe-inline' https://commons.wikimedia.org/; form-action 'self' https://mail.clubs.uci.edu/;"
    db_user: mediawiki
    db_name: mediawiki
    script_path: /w
    article_path: wiki
    wiki_name: "LUG@UCI"
    wiki_namespace: "LUG"
    admin_user: "Admin"
# NOTE: This "Admin" user should never exist, as we already have existing data. If it gets created, something has gone seriously wrong.

- name: Wiki uploads
  hosts: web
  become: yes
  become_user: root
  roles:
    - apache2-site
  vars:
    domain: uploads.ucilug.org
    cert_domain: ucilug.org
    enable_https: True
    enable_hsts: True
    referrer_policy: same-origin
    x_frame_options: SAMEORIGIN
    content_security_policy: "sandbox; default-src 'none'; style-src 'self' 'unsafe-inline';"

- name: www.ucilug.org redirect
  hosts: web
  become: yes
  become_user: root
  roles:
    - apache2-redirect
  vars:
    domain: www.ucilug.org
    cert_domain: ucilug.org
    target: https://ucilug.org/
    enable_https: True
    enable_hsts: True
    referrer_policy: strict_origin
    x_frame_options: SAMEORIGIN
    content_security_policy: "sandbox; default-src 'self';"


