---
- name: Create directory structure
  file:
    path: "/var/www/{{ domain }}/logs"
    state: directory
    owner: www-data
    group: www-data

- name: Enable mod_ssl
  apache2_module:
    name: ssl
    state: present
  when: enable_https is defined and enable_https
  register: apache2redirect_modssl

- name: Copy configuration file
  template:
    src: apache2.conf.j2
    dest: "/etc/apache2/sites-available/{{ domain }}.conf"
  register: apache2redirect_copyconfig

- name: Enable site
  command: "a2ensite {{ domain }}"
  register: apache2redirect_enablesite
  changed_when: '"Enabling site " in apache2redirect_enablesite.stdout'
  failed_when: '"ERROR: " in apache2redirect_enablesite.stdout'

- name: Reload apache2
  systemd:
    name: apache2
    state: reloaded
  register: apache2redirect_reload
  when: apache2redirect_copyconfig.changed or apache2redirect_enablesite.changed

- name: Restart apache2
  systemd:
    name: apache2
    state: restarted
  when: apache2redirect_modssl.changed

